language: android
jdk: oraclejdk8
sudo: true

env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - TRAVIS_SECURE_ENV_VARS=true

android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository
    - extra-google-android-support
    - extra-android-support
    # The SDK version used to compile your project

  before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew
script:
     - gradlew build connectedCheck
#    - ./gradle clean
#    - ./gradlew install
#    - ./gradlew bintrayUpload
    - ./gradlew assembleDebug

#before_deploy:       # 部署之前
#   # 使用 mv 命令进行修改apk文件的名字
#   - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/buff.apk
#
#deploy:              # 部署
#   provider: releases # 部署到GitHub Release，除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
#   api_key:           # 填写GitHub的token （Settings -> Personal access tokens -> Generate new token）
#     secure: 7f4dc45a19f742dce39cbe4d1e5852xxxxxxxxx
#   file: app/build/outputs/apk/buff.apk   # 部署文件路径
#   skip_cleanup: true     # 设置为true以跳过清理,不然apk文件就会被清理
#   on:     # 发布时机
#     tags: true       # tags设置为true表示只有在有tag的情况下才部署