language: android
jdk: oraclejdk8
sudo: true
before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew
env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - TRAVIS_SECURE_ENV_VARS=true

android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - extra-android-m2repository
    - extra-google-android-support
    - extra-android-support
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

  before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

  licenses:
    - '.+'

script:
    - ./gradle clean
#    - ./gradlew install
#    - ./gradlew bintrayUpload
    - ./gradle assembleDebug